import type { Banner } from '@/types/banner'
import type { Category } from '@/types/category'

const seller = {
  _id: 'demo-seller-kourier-boyz',
  name: 'Kourier Boyz Demo Seller',
  storeName: 'Kourier Boyz Picks',
  storeDescription: 'Curated products with marketplace-ready shipping.',
  storeSlug: 'kourier-boyz-picks',
  sellerRating: 4.8,
  sellerReviewCount: 426,
}

const category = (
  slug: string,
  name: string,
  image: string,
) => ({
  _id: `demo-category-${slug}`,
  name,
  slug,
  mainImage: image,
})

const demoSubcategory = (
  parent: string,
  id: string,
  name: string,
  slug: string,
  image: string,
  description: string,
): Category => ({
  _id: id,
  name,
  slug,
  description,
  mainImage: image,
  hoverImage: image,
  banners: [],
  top: true,
  status: 'active',
  parent,
  productCount: 120,
})

export const demoProducts = [
  {
    _id: 'demo-classic-tshirt',
    name: 'Classic Everyday Cotton T-Shirt',
    slug: 'classic-everyday-cotton-t-shirt',
    description: 'Soft breathable cotton tee made for everyday wear and fast dispatch.',
    shortDescription: 'Soft cotton tee with quick delivery.',
    price: 599,
    effectivePrice: 499,
    comparePrice: 799,
    mainImage: '/products/tshirt.jpg',
    images: ['/products/tshirt.jpg'],
    category: category('fashion', 'Fashion', '/products/tshirt.jpg'),
    seller,
    brand: 'Kourier Basics',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 128,
    soldCount: 1840,
    viewCount: 9200,
    discountPercent: 38,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 86,
    totalStock: 86,
    freeShipping: true,
    returnable: true,
    returnDays: 7,
    payOnDelivery: true,
    tags: ['fashion', 'daily wear', 'cotton'],
  },
  {
    _id: 'demo-smart-watch',
    name: 'Smart Watch Series 5',
    slug: 'smart-watch-series-5',
    description: 'Fitness tracking, call alerts, and a bright display in a lightweight body.',
    shortDescription: 'Fitness watch with bright display.',
    price: 3500,
    effectivePrice: 2999,
    comparePrice: 4499,
    mainImage: '/products/watch.webp',
    images: ['/products/watch.webp'],
    category: category('electronics', 'Electronics', '/products/watch.webp'),
    seller,
    brand: 'PulseFit',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 246,
    soldCount: 2630,
    viewCount: 14050,
    discountPercent: 33,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 42,
    totalStock: 42,
    freeShipping: true,
    returnable: true,
    warranty: true,
    warrantyDays: 180,
    tags: ['electronics', 'watch', 'fitness'],
  },
  {
    _id: 'demo-accent-chair',
    name: 'Modern Accent Chair',
    slug: 'modern-accent-chair',
    description: 'A clean modern accent chair for living rooms, bedrooms, and reading corners.',
    shortDescription: 'Modern chair for cozy spaces.',
    price: 6400,
    effectivePrice: 5799,
    comparePrice: 7499,
    mainImage: '/products/chair.jpg',
    images: ['/products/chair.jpg'],
    category: category('home-living', 'Home & Living', '/products/chair.jpg'),
    seller,
    brand: 'RoomCraft',
    status: 'active' as const,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 74,
    soldCount: 420,
    viewCount: 5110,
    discountPercent: 23,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 18,
    totalStock: 18,
    freeShipping: false,
    returnable: true,
    tags: ['home', 'furniture', 'chair'],
  },
  {
    _id: 'demo-shopper-tote',
    name: 'Daily Shopper Tote Bag',
    slug: 'daily-shopper-tote-bag',
    description: 'Roomy everyday tote for work, errands, gifting, and easy shipping.',
    shortDescription: 'Roomy everyday carry tote.',
    price: 1199,
    effectivePrice: 899,
    comparePrice: 1499,
    mainImage: '/shop2.png',
    images: ['/shop2.png'],
    category: category('bags', 'Bags', '/shop2.png'),
    seller,
    brand: 'CarryWell',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 93,
    soldCount: 990,
    viewCount: 6200,
    discountPercent: 40,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 64,
    totalStock: 64,
    freeShipping: true,
    returnable: true,
    payOnDelivery: true,
    tags: ['bag', 'fashion', 'travel'],
  },
  {
    _id: 'demo-home-organizer',
    name: 'Foldable Home Organizer Box',
    slug: 'foldable-home-organizer-box',
    description: 'A sturdy storage box for wardrobes, shelves, and marketplace-ready home bundles.',
    shortDescription: 'Foldable storage for home essentials.',
    price: 899,
    effectivePrice: 699,
    comparePrice: 1099,
    mainImage: '/cart.png',
    images: ['/cart.png'],
    category: category('home-living', 'Home & Living', '/cart.png'),
    seller,
    brand: 'NeatNest',
    status: 'active' as const,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 61,
    soldCount: 710,
    viewCount: 3900,
    discountPercent: 36,
    stock: 110,
    totalStock: 110,
    freeShipping: true,
    returnable: true,
    tags: ['home', 'storage', 'organizer'],
  },
  {
    _id: 'demo-sneakers',
    name: 'Street Flex Sneakers',
    slug: 'street-flex-sneakers',
    description: 'Lightweight sneakers with a comfortable sole for all-day movement.',
    shortDescription: 'Comfortable sneakers for daily wear.',
    price: 1999,
    effectivePrice: 1499,
    comparePrice: 2499,
    mainImage: '/home-banner.png',
    images: ['/home-banner.png'],
    category: category('footwear', 'Footwear', '/home-banner.png'),
    seller,
    brand: 'UrbanStep',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 188,
    soldCount: 1320,
    viewCount: 8450,
    discountPercent: 40,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 55,
    totalStock: 55,
    freeShipping: true,
    returnable: true,
    tags: ['fashion', 'footwear', 'sneakers'],
  },
  {
    _id: 'demo-wireless-earbuds',
    name: 'Pocket Wireless Earbuds',
    slug: 'pocket-wireless-earbuds',
    description: 'Compact wireless earbuds with clear calls, touch controls, and an easy-carry charging case.',
    shortDescription: 'Clear everyday audio in a compact case.',
    price: 2199,
    effectivePrice: 1699,
    comparePrice: 2999,
    mainImage: '/products/watch.webp',
    images: ['/products/watch.webp'],
    category: category('electronics', 'Electronics', '/products/watch.webp'),
    seller,
    brand: 'SonicGo',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 174,
    soldCount: 1580,
    viewCount: 8700,
    discountPercent: 43,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 73,
    totalStock: 73,
    freeShipping: true,
    returnable: true,
    warranty: true,
    warrantyDays: 180,
    tags: ['electronics', 'audio', 'earbuds'],
  },
  {
    _id: 'demo-travel-duffle',
    name: 'Weekender Travel Duffle',
    slug: 'weekender-travel-duffle',
    description: 'A structured cabin-friendly duffle with separate pockets for shoes, cables, and small essentials.',
    shortDescription: 'Organised cabin-ready weekender bag.',
    price: 2499,
    effectivePrice: 1899,
    comparePrice: 3199,
    mainImage: '/shop2.png',
    images: ['/shop2.png'],
    category: category('bags-travel', 'Bags & Travel', '/shop2.png'),
    seller,
    brand: 'CarryWell',
    status: 'active' as const,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 112,
    soldCount: 880,
    viewCount: 5430,
    discountPercent: 41,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 37,
    totalStock: 37,
    freeShipping: true,
    returnable: true,
    tags: ['bag', 'travel', 'duffle'],
  },
  {
    _id: 'demo-reading-lamp',
    name: 'Warm Glow Reading Lamp',
    slug: 'warm-glow-reading-lamp',
    description: 'A compact bedside lamp with three brightness levels and a warm, comfortable reading light.',
    shortDescription: 'Adjustable warm light for desks and bedsides.',
    price: 1599,
    effectivePrice: 1199,
    comparePrice: 1899,
    mainImage: '/products/chair.jpg',
    images: ['/products/chair.jpg'],
    category: category('home-living', 'Home & Living', '/products/chair.jpg'),
    seller,
    brand: 'RoomCraft',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 89,
    soldCount: 760,
    viewCount: 4180,
    discountPercent: 37,
    stock: 48,
    totalStock: 48,
    freeShipping: true,
    returnable: true,
    tags: ['home', 'lighting', 'gift'],
  },
  {
    _id: 'demo-care-kit',
    name: 'Daily Skin Care Essentials Kit',
    slug: 'daily-skin-care-essentials-kit',
    description: 'A simple cleanser, moisturiser, and lip-care trio packed for everyday routines and gifting.',
    shortDescription: 'Three daily care essentials in one kit.',
    price: 1299,
    effectivePrice: 949,
    comparePrice: 1599,
    mainImage: '/cart.png',
    images: ['/cart.png'],
    category: category('beauty-care', 'Beauty & Care', '/cart.png'),
    seller,
    brand: 'DailyKind',
    status: 'active' as const,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 138,
    soldCount: 1210,
    viewCount: 6950,
    discountPercent: 41,
    stock: 95,
    totalStock: 95,
    freeShipping: true,
    returnable: false,
    tags: ['beauty', 'care', 'skincare', 'gift'],
  },
  {
    _id: 'demo-relaxed-polo',
    name: 'Relaxed Fit Polo Shirt',
    slug: 'relaxed-fit-polo-shirt',
    description: 'A breathable pique-knit polo with an easy fit for office days, travel, and weekends.',
    shortDescription: 'Breathable polo with an easy everyday fit.',
    price: 1099,
    effectivePrice: 799,
    comparePrice: 1399,
    mainImage: '/products/tshirt.jpg',
    images: ['/products/tshirt.jpg'],
    category: category('fashion', 'Fashion', '/products/tshirt.jpg'),
    seller,
    brand: 'Kourier Basics',
    status: 'active' as const,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 97,
    soldCount: 1040,
    viewCount: 5860,
    discountPercent: 43,
    stock: 82,
    totalStock: 82,
    freeShipping: true,
    returnable: true,
    returnDays: 7,
    payOnDelivery: true,
    tags: ['fashion', 'shirt', 'cotton', 'wear'],
  },
  {
    _id: 'demo-gift-box',
    name: 'Everyday Favourites Gift Box',
    slug: 'everyday-favourites-gift-box',
    description: 'A ready-to-send gift box with a notebook, insulated cup, and thoughtful desk essentials.',
    shortDescription: 'A practical gift set, packed and ready to send.',
    price: 1799,
    effectivePrice: 1399,
    comparePrice: 2199,
    mainImage: '/home-banner.png',
    images: ['/home-banner.png'],
    category: category('flash-deals', 'Gift Essentials', '/home-banner.png'),
    seller,
    brand: 'GoodParcel',
    status: 'active' as const,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 66,
    soldCount: 690,
    viewCount: 3740,
    discountPercent: 36,
    discountEnd: '2026-12-31T23:59:59.000Z',
    stock: 29,
    totalStock: 29,
    freeShipping: true,
    returnable: true,
    tags: ['gift', 'accessory', 'essentials'],
  },
]

export const demoBanners: Banner[] = [
  {
    _id: 'demo-hero-bazaar',
    title: 'Chosen well. Delivered with care.',
    subtitle: 'Useful fashion, home, beauty, and tech from growing Indian sellers.',
    image: '/brand/kourier-boyz-commerce-hero.webp',
    link: '/shop',
    linkText: 'Shop Now',
    position: 'hero',
    active: true,
    order: 1,
  },
  {
    _id: 'demo-hero-seller',
    title: 'A store that already knows how to ship.',
    subtitle: 'Build your catalogue, receive orders, and dispatch without leaving the seller panel.',
    image: '/brand/kourier-boyz-hero.webp',
    link: '/ship',
    linkText: 'Start Shipping',
    position: 'hero',
    active: true,
    order: 2,
  },
]

export const demoSectionBanners: Record<Banner['position'], Banner[]> = {
  hero: demoBanners,
  deals: [
    {
      _id: 'demo-deals-banner',
      title: 'Flash Deals Across Categories',
      subtitle: 'Limited-time demo offers on fashion, electronics, home, and more.',
      image: '/cart.png',
      link: '/events/deals',
      linkText: 'View Offers',
      position: 'deals',
      active: true,
      order: 1,
    },
  ],
  fashion: [
    {
      _id: 'demo-fashion-banner',
      title: 'Everyday Fits, Easy Returns',
      subtitle: 'Comfort-first styles shipped with marketplace-grade tracking.',
      image: '/products/tshirt.jpg',
      link: '/shop',
      linkText: 'Explore Fashion',
      position: 'fashion',
      active: true,
      order: 1,
    },
  ],
  trending: [
    {
      _id: 'demo-trending-banner',
      title: 'Trending Now',
      subtitle: 'Popular picks moving fast through the Kourier Boyz network.',
      image: '/products/watch.webp',
      link: '/shop',
      linkText: 'Browse Trending',
      position: 'trending',
      active: true,
      order: 1,
    },
  ],
  featured: [],
  newsletter: [],
}

export const demoCategories: Category[] = [
  {
    _id: 'demo-category-fashion',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Daily wear, casual styles, and quick-selling basics.',
    mainImage: '/products/tshirt.jpg',
    hoverImage: '/home-banner.png',
    banners: [],
    top: true,
    status: 'active',
    productCount: 1240,
    subcategories: [
      demoSubcategory('demo-category-fashion', 'demo-sub-fashion-clothing', 'Everyday Clothing', 'everyday-clothing', '/products/tshirt.jpg', 'Comfortable clothing and dependable daily basics.'),
      demoSubcategory('demo-category-fashion', 'demo-sub-fashion-footwear', 'Footwear', 'footwear', '/home-banner.png', 'Sneakers and practical footwear for daily movement.'),
    ],
  },
  {
    _id: 'demo-category-electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Useful gadgets and accessories for modern buyers.',
    mainImage: '/products/watch.webp',
    hoverImage: '/products/watch.webp',
    banners: [],
    top: true,
    status: 'active',
    productCount: 860,
    subcategories: [
      demoSubcategory('demo-category-electronics', 'demo-sub-electronics-wearables', 'Wearables', 'wearables', '/products/watch.webp', 'Smart watches and useful personal technology.'),
      demoSubcategory('demo-category-electronics', 'demo-sub-electronics-audio', 'Personal Audio', 'personal-audio', '/products/watch.webp', 'Compact audio accessories for work and travel.'),
    ],
  },
  {
    _id: 'demo-category-home',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Decor, furniture, and home essentials.',
    mainImage: '/products/chair.jpg',
    hoverImage: '/cart.png',
    banners: [],
    top: true,
    status: 'active',
    productCount: 720,
    subcategories: [
      demoSubcategory('demo-category-home', 'demo-sub-home-furniture', 'Furniture', 'furniture', '/products/chair.jpg', 'Furniture for comfortable, functional spaces.'),
      demoSubcategory('demo-category-home', 'demo-sub-home-storage', 'Storage', 'storage', '/cart.png', 'Simple organization for wardrobes and shelves.'),
    ],
  },
  {
    _id: 'demo-category-bags',
    name: 'Bags & Travel',
    slug: 'bags-travel',
    description: 'Totes, carry bags, and travel-friendly accessories.',
    mainImage: '/shop2.png',
    hoverImage: '/shop2.png',
    banners: [],
    top: true,
    status: 'active',
    productCount: 510,
    subcategories: [
      demoSubcategory('demo-category-bags', 'demo-sub-bags-everyday', 'Everyday Bags', 'everyday-bags', '/shop2.png', 'Totes and carry bags for everyday routines.'),
      demoSubcategory('demo-category-bags', 'demo-sub-bags-travel', 'Travel Bags', 'travel-bags', '/shop2.png', 'Roomy carry options for short trips and dispatch.'),
    ],
  },
  {
    _id: 'demo-category-deals',
    name: 'Flash Deals',
    slug: 'flash-deals',
    description: 'High-value picks with active discounts.',
    mainImage: '/cart.png',
    hoverImage: '/home-banner.png',
    banners: [],
    top: true,
    status: 'active',
    productCount: 340,
    subcategories: [
      demoSubcategory('demo-category-deals', 'demo-sub-beauty-care', 'Beauty & Care', 'beauty-care', '/cart.png', 'Personal care essentials at useful prices.'),
      demoSubcategory('demo-category-deals', 'demo-sub-gifts-essentials', 'Gift Essentials', 'gift-essentials', '/products/watch.webp', 'Easy-to-gift accessories and everyday favourites.'),
    ],
  },
]
